### ISSUE TITLE
Flag to chose between IRB & Pry?

### ISSUE THREAD

**Issue by qortex** [davidcelis/rack-console#2]
Would it be possible to add a flag to make the choosing between IRB and PRY explicit, instead of trying to load PRY and fallback to IRB if it fails in [this method](https://github.com/davidcelis/rack-console/blob/747d748d9f7af36654ce9868c43ff9031c312585/lib/rack/console.rb#L32)?

Thanks for the very useful gem :)

**Comment by davidcelis** [comment]
@qortex it's definitely _possible_, but is there a reason you'd want to force IRB over Pry? to me this feels like something that would fall outside of what most users of this gem would want

**Comment by qortex** [comment]
I personnally don't use the additional features from Pry, but like the new IRB with multiline & syntax highlighting support.
Just personal taste though. Right now I just don't have Pry installed and it's ok. But if someday I'd like to have pry in parallel for a debug session, it would be used in rack-console which wouldn't be the desired effect.

Happy to agree it might not be common taste though, I don't know :)

**Comment by davidcelis** [comment]
No worries. I understand, but I'd estimate that in 99% of cases, if someone has Pry installed then they want to use it. Gonna close this out. Sorry!

**Comment by qortex** [comment]
Fair enough!

**Comment by qortex** [comment]
hey, hit that again. I now use Zeitwerk that monkey-patches `require` calls. Now, the "pry or irb" code doesn't work. Instead of using the flag as intended, it throws:
```sh
`require': cannot load such file -- pry (LoadError)
Did you mean?  pty
```

It is not handy.

Would it justify a flag in your opinion?

**Comment by davidcelis** [comment]
@qortex Sorry, I'm a little confused; what exactly have you hit here? Originally the proposed flag was just to force IRB or Pry instead of trying Pry and falling back to IRB. The `require` statement for Pry is wrapped in a `rescue LoadError` statement, so I'm not totally understanding why the `LoadError` would bubble up. Do you have a full trace and/or a sample app?

**Comment by qortex** [comment]
Yeah I'm a bit puzzled too actually. Here is a typical stack trace below when I raise an exception with the code I write in the console.

I don't quite get why it jumps back to that place in the code with a second fail, as if a new execution took place.
Do you see what could be at play?

I start my process with `bundle exec rack-console`.

```
(irb):5:in `<main>': undefined method `schema' for Sqan::Models::Unknown:Class (NoMethodError)
Did you mean?  db_schema
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-console-1.3.1/lib/rack/console.rb:37:in `rescue in start'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-console-1.3.1/lib/rack/console.rb:32:in `start'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-console-1.3.1/bin/rack-console:33:in `<top (required)>'
	from /home/mic/.rbenv/versions/3.0.2/bin/rack-console:25:in `load'
	from /home/mic/.rbenv/versions/3.0.2/bin/rack-console:25:in `<top (required)>'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:478:in `exec'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/exe/bundle:49:in `block in <top (required)>'
	... 4 levels...
/home/mic/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- pry (LoadError)
Did you mean?  pty
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-console-1.3.1/lib/rack/console.rb:33:in `start'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/rack-console-1.3.1/bin/rack-console:33:in `<top (required)>'
	from /home/mic/.rbenv/versions/3.0.2/bin/rack-console:25:in `load'
	from /home/mic/.rbenv/versions/3.0.2/bin/rack-console:25:in `<top (required)>'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:478:in `exec'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:25:in `start'
	from /home/mic/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/exe/bundle:49:in `block in <top (required)>'
	... 4 levels...
```

**Comment by davidcelis** [comment]
Hmmmm, this doesn't really seem like an exception being raised by `rack-console` is the issue here. I'm assuming that if you don't call `Sqan::Models::Unknown.schema`, there's no problem? Without truly understanding what Zeitwork is doing in their `require` monkeypatch, it seems as though its simply preserving the fact that there was a `LoadError` at some point in the callstack. Confusing, but it seems harmless to me

**Comment by qortex** [comment]
yes exactly, if I don't throw in my own code, it behaves properly.
yeah very confusing, but zeitwerk is some very clever black magic, so side effects in unusual settings might happen.
Indeed harmless, since it happens only when there already is an exception upstream.
I'll try to fork & add the pry/irb setting to see if it smoothes things up, it's mainly just practical for me (the second part of the error take up all the console screen when I'm interested only in the first part). I'll push a PR if you're interested.

**Comment by davidcelis** [comment]
To be honest, unless this is something being caused by my gem in particular, I think I wouldn't be likely to accept a PR just to clean up backtraces that are being caused by a completely different dependency 😅 It seems like you would experience this issue with any other `LoadError` your application encountered, so I would probably raise this issue with the maintainers of Zeitwerk if its behavior you'd like to see changed!

**Comment by taylorthurlow** [comment]
Pry is in my gemfile.lock only as a transitive dependency (in this case of `guard`), and I want to use IRB over pry. I basically have no control over that. So I would also appreciate the ability to explicitly choose irb.

**Comment by davidcelis** [comment]
@taylorthurlow Ahhh that makes a lot of sense, I hadn't considered transitive dependencies when this issue was originally opened

**Comment by davidcelis** [comment]
A mere five years later, and I'm pleased to announce that Pry is now opt-in as of [v2.0.0](https://github.com/davidcelis/rack-console/releases/tag/v2.0.0). Thanks for your patience!
